### PR TITLE
Create sorting_segments.cpp

### PR DESCRIPTION
**Pull request by SwetaDas16**

### CODE REVIEW

**Comment by vaibhavagarwal47** [comment]
It is given in the template to mention the question code or the question link. Mention the required to merge the PR.

**Comment by SwetaDas16** [comment]
https://www.codechef.com/SNCKEL21/problems/SORTSEGS

**Comment by vaibhavagarwal47** [comment]
It should be mentioned at the starting of the file. just refer to the template given. I will accept the PR but comply to the template.

**Comment by vaibhavagarwal47** [comment]
Great!

**Pull request merged**
